### ISSUE TITLE
/usr/share/dict/words?

### ISSUE THREAD

**Issue by alphapapa** [mrkkrp/typit#1]
Hi, I see that you use your own dictionaries.  Have you thought about using `/usr/share/dict/words` and other system dictionaries?

**Comment by mrkkrp** [comment]
On my system (Arch Linux) there is no such file by default. I'm not sure you can find anything like this on Windows (people use Windows). I think it's safer to just use dictionary that comes with the package. Another good thing about it is that I have full control over it ;-)

**Comment by alphapapa** [comment]
Hm, on Debian/Ubuntu it's provided by `dictionaries-common` and individual dicts like `wamerican`.  I wonder what the equivalent on Arch is.

**Comment by mrkkrp** [comment]
Well, but how do we deal with Windows?

**Comment by alphapapa** [comment]
I don't know.  That's one of the problems with Windows, of course, the lack of standard things like that.  There's also Cygwin, which probably installs it with aspell when you install Emacs.  But for pure win32...

I mean, you could use it optionally, if it exists.  But I was just throwing out an idea.  :)

**Comment by mrkkrp** [comment]
Anyway, I think it's better to come with “batteries included”, than tell user, “you know, you need to install package X to use it”. Thanks for the suggestion anyway.

**Comment by mrkkrp** [comment]
Closing, as it's unlikely that something like this will be added.
