### ISSUE TITLE
Avoid change of typit.el code in order to add other languages

### ISSUE THREAD

**Issue by technician77** [mrkkrp/typit#2]
Please enhance the code so that adding another language does not require changing typit.el. This has two reasons. First for people not familar with coding (like me) it might impose a challenge to change the code, even for that simple change. I manged to solve this, but there is another more important reason: If you update typit.el through melpa then the user has to change the code again. I'm not sure what happens to the subdirectory dict when an update occurs but in the worst case the added language text file has to added also again. So it might make sense not to ask the user to put the "yourlanguagefile.txt" inside dict inside the package subdirectory. It has to be a directory which is save from removing/updating the package.

**Comment by mrkkrp** [comment]
It's assumed that dictionaries are added in the repo, not locally. If you want to add a dictionary, open a pull request and then your dictionary will be with you everywhere as part of installation.

**Comment by technician77** [comment]
Mrkkrp, this ain't that easy. "My" dictionary is not mine it is the dictionary of University Leipzig Germany. The 1000 most common words in german is put together using scientific methods. Additionally language is dynamic and as a result the words on the list change.

As far as I can see the list is free for private and scientific use but not for commercial use. I'm no lawyer but I assume putting it inside the repo is not legal.

Link to list: http://wortschatz.uni-leipzig.de/Papers/top1000de.txt
Link to license terms: http://wortschatz.uni-leipzig.de/use.html

Since this is a general problem you might consider my original post. Great would be a "fetch that dictionary from that url and put it in ~/.emacs.d/typit/dicts/" function or something similar.

**Comment by mrkkrp** [comment]
Putting it into the repo of open-source project does not constitute commercial use, AFAIK. I do not make profit from this code in any way and I do not plan to do it. We could put an alert into readme file that this particular dictionary cannot be used for commercial purposes and point to the license page.

Function that would fetch the dictionary dynamically is sort of easy, this can be done.

**Comment by technician77** [comment]
I'm no lawyer, but I see potential risks here. If you put it in the repo
you take the risk.

The get-url-function would solve this problem also for all other
dictionaries. Additionally a current dict could be always pulled (if it's a
dynamically created list).

I have seen that the university of leipzig provides lists for german, dutch
and english. Top 100, Top 1000 and Top 10000.

http://wortschatz.uni-leipzig.de/Papers/top1000nl.txt
http://wortschatz.uni-leipzig.de/Papers/top1000en.txt
http://wortschatz.uni-leipzig.de/Papers/top1000fr.txt

Another solution would be to add the use of open source packages like
aspell. They offer a lot of languages and are open source without a
commercial use restriction. Problem there is that they contain many words
that are not commonly used. But is this really a problem?

If you just add either functionality and keep your included english file
you still have some basic fulfilment of your "Batteries included" approach.

2016-05-07 8:33 GMT+02:00 Mark Karpov notifications@github.com:

> Putting it into the repo of open-source project does not constitute
> commercial use, AFAIK. I do not make profit from this code in any way and I
> do not plan to do it. We could put an arert into readme file that this
> particular dictionary cannot be used for commercial purposes and point to
> the license page.
> 
> Function that would fetch the dictionary dynamically is sort of easy, this
> can be done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mrkkrp/typit/issues/2#issuecomment-217611352

## 

Mit freundlichen Grüssen / With kind regards:
Jens Lange

**Comment by technician77** [comment]
Correction:
The languages from uni-leipzig are german, dutch, english, french. Just
replace 1000 with 100 or 10000 for the other lists:

http://wortschatz.uni-leipzig.de/Papers/top1000de.txt
http://wortschatz.uni-leipzig.de/Papers/top1000nl.txt <goog_2012547998>

<goog_2012547998>
http://wortschatz.uni-leipzig.de/Papers/top1000en.txt <goog_2012547998>

<goog_2012547998>
http://wortschatz.uni-leipzig.de/Papers/top1000fr.txt

---------- Forwarded message ----------
From: Jens Lange jens.lange.de@gmail.com
Date: 2016-05-08 5:36 GMT+02:00
Subject: Re: [mrkkrp/typit] Avoid change of typit.el code in order to add
other languages (#2)
To: mrkkrp/typit <
reply@reply.github.com


I'm no lawyer, but I see potential risks here. If you put it in the repo
you take the risk.

The get-url-function would solve this problem also for all other
dictionaries. Additionally a current dict could be always pulled (if it's a
dynamically created list).

I have seen that the university of leipzig provides lists for german, dutch
and english. Top 100, Top 1000 and Top 10000.

http://wortschatz.uni-leipzig.de/Papers/top1000de.txt
http://wortschatz.uni-leipzig.de/Papers/top1000nl.txt

http://wortschatz.uni-leipzig.de/Papers/top1000nl.txt

http://wortschatz.uni-leipzig.de/Papers/top1000en.txt

http://wortschatz.uni-leipzig.de/Papers/top1000fr.txt

Another solution would be to add the use of open source packages like
aspell. They offer a lot of languages and are open source without a
commercial use restriction. Problem there is that they contain many words
that are not commonly used. But is this really a problem?

If you just add either functionality and keep your included english file
you still have some basic fulfilment of your "Batteries included" approach.

2016-05-07 8:33 GMT+02:00 Mark Karpov notifications@github.com:

> Putting it into the repo of open-source project does not constitute
> commercial use, AFAIK. I do not make profit from this code in any way and I
> do not plan to do it. We could put an arert into readme file that this
> particular dictionary cannot be used for commercial purposes and point to
> the license page.
> 
> Function that would fetch the dictionary dynamically is sort of easy, this
> can be done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mrkkrp/typit/issues/2#issuecomment-217611352

## 

Mit freundlichen Grüssen / With kind regards:
Jens Lange

## 

Mit freundlichen Grüssen / With kind regards:
Jens Lange

**Comment by technician77** [comment]
Thanks for adding the 10k german dictionary.
