### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by erdmenger** [mrkkrp/typit#8]
Hi Mark, thank you for making this nice project public.
Eventually I would like to contribute by adding a German dictionary which I already tested locally and maybe modify the dictionary selection function.
Before doing so I like to have clarity on the license you like to use for this project.
Personally I suggest an MIT like license, since it makes reuse and contribution very easy without forcing anything: https://opensource.org/licenses/MIT
I will create a pull request and add the file. Up to you if you like to accept or use another one.

**Comment by erdmenger** [comment]
Sorry I just realized you like to use GPL v3 as mentioned in the last lines of README.md. 
That would conflict with the dictionary I planned to contribute.

**Comment by mrkkrp** [comment]
Hi, we (Emacs users) can't really use anything but GNU GPL because the packages are derivative works based on Emacs itself, which is licensed under GNU GPL v3 and so we are forced to use this license for open source packages.

**Comment by erdmenger** [comment]
I got written confirmation from Antje Schlaf, Natural Language Processing Group with permission to use their word list in my 'non-commercial'' projects. So I created a pull request to add the german dictionary.

Thanks for considering a merge.
Joerg


Confirmation mail (german):
> Sehr geehrter Herr Erdmenger,
> vielen Dank für Ihre Email. Sie können die Wortliste gerne in Ihren nicht-kommerziellen Projekten verwenden.
> Wir haben eine Download-Seite auf der Sie u.a. Wortlisten für zahlreiche Sprachen herunterladen können: http://corpora2.informatik.uni-leipzig.de/download.html
> Dort finden Sie auch den Lizenzhinweis (unter der Überschrift "Conditions of use" bzw. direkt unter http://wortschatz.uni-leipzig.de/use.html).
> . . .
> 
> Antje Schlaf
> Natural Language Processing Group
